export const GLOBAL_CONSTRUCTORS = {
  /**
   * AggregateError was introduced in Node v15.
   */
  ...((typeof AggregateError === 'undefined' ? {} : { AggregateError }) as {
    AggregateError: AggregateErrorConstructor;
  }),
  Array,
  ArrayBuffer,
  BigInt64Array,
  BigUint64Array,
  Boolean,
  DataView,
  Date,
  Error,
  EvalError,
  FinalizationRegistry,
  Float32Array,
  Float64Array,
  Function,
  Int16Array,
  Int32Array,
  Int8Array,
  Map,
  Number,
  Object,
  Promise,
  RangeError,
  ReferenceError,
  RegExp,
  Set,
  SharedArrayBuffer,
  String,
  SyntaxError,
  TypeError,
  URIError,
  Uint16Array,
  Uint32Array,
  Uint8Array,
  Uint8ClampedArray,
  WeakMap,
  WeakRef,
  WeakSet,
};
